sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jifjJgsynmCskg/sfcHDAp/GzuSB+QyZZXlspmdtqE56xp3KINOAGYc7yhtIbVjuZQsl7Eb40ilj6lewJyySH4ihsOmQcwGhO9wNZ+GWHL0wdkaN2i+lgXYhigJdsn4h1GamB6fKjsSQPqTi98i3JFfPGt/eu3akIk7klDeNHuAtV+D3mIbKI0C2Oh4i9FTKVZZGIIAkK+X0TauB7AI7LfkxbhCKmfFdJSiJZQj71SgZyFgQKNEzlZmikTkivUKriHDc47pKrbJynEJDEpRWlf7AVuxYHE3I/lXZZ0QQ/FaqJJiYPsnkmHpdQydoMYi8eBDAWSNORjIEpji2LFFkhKWFX9XH9cvk/h/EzVf925XoSChlmKVKek1VpHjyrItFijbVspJT0les5Xa40rhxkwmsXMMwz9Yzm0yR06AaW2KIewL6C8nnzT8h2TKedssvfg7umY13DFVydOjrVHhlpg/lGO9tcBtDNDtHzs6cDP4EU1gGvApuRbhITv3XM7ywVBDpNXFrJxCD1+LW3ml/mc3RYA4Twl0AOUqJTVUBUIIW1D8mcgeKWeC/TvhzjwWaWV16ENBtNR51WoflYTk8qisoXQ9Fax9nrbIwfCowNlxrlCdLo8ruCElnKlUBRXSFmew/CmzJFIzXjqWrbqTzBN+pM+GZfP1RZRhjsz9kb5Y=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Word-Only-a-Word-Volume-05_5576
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy